todo/urls.py
from django.urls import path

from todo.views import (
    HomePage,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    complete_or_undo_task
)

urlpatterns = [
    path("", HomePage.as_view(), name="task-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/complete/", complete_or_undo_task, name="complete-task"),
    path("task/<int:pk>/undo/", complete_or_undo_task, name="undo-task"),
    path("tags", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete")
]

app_name = "todo"

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tags")

    class Meta:
        ordering = ["is_done", "-created_date"]

    def __str__(self):
        return {self.content}

todo/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.models import Task, Tag


class HomePage(generic.ListView):
    template_name = "index.html"
    queryset = Task.objects.all()


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")
    template_name = "task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")
    template_name = "task_form.html"


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")
    template_name = "task_confirm_delete.html"


class TagListView(generic.ListView):
    template_name = "tag_list.html"
    queryset = Tag.objects.all()


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "tag_form.html"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")
    template_name = "tag_confirm_delete.html"


def complete_or_undo_task(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_done:
        task.is_done = False
    else:
        task.is_done = True
    task.save()
    return redirect("todo:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>TODO</title>
  {% endblock %}
  <meta charset="utf=8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static "css/styles.css" %}">

</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %} {% include "includes/sidebar.html" %} {% endblock %}
      </div>
      <div class="col-sm-10">
        {% block content %} {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item">
    <a class="sidebar-link" href="{% url 'todo:task-list' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a class="sidebar-link" href="{% url 'todo:tag-list' %}">Tags</a>
  </li>
</ul>

templates/index.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h1>
      TODO list
      <a style="float:right" class="btn btn-primary" href="{% url 'todo:task-create' %}">Add task</a>
    </h1>
  </div>
  <br>
  {% if task_list %}
    <ul class="task-list">
      {% for task in task_list %}
        <li>
          <p><b>{{ task.content }}
            {% if task.is_done %}
              <span style="color: green">Done</span>
              <a style="float:right" class="btn btn-secondary" href="{% url 'todo:undo-task' pk=task.id %}">Undo</a>
            {% else %}
              <span style="color: red">Not done</span>
              <a style="float:right" class="btn btn-success" href="{% url 'todo:complete-task' pk=task.id %}">Complete</a>
            {% endif %}
          </b></p>
          <p>
            Created: {{ task.created_date }}
            {% if task.deadline %}
              <span style="color: darkred">Deadline: {{ task.deadline }}</span>
            {% endif %}
          </p>
          <p class="tags" style="color: grey">
            Tags:
            {% for tag in task.tags.all %}
              {{ tag.name }}
            {% endfor %}
            <a href="{% url 'todo:task-update' pk=task.id %}">Update</a>
            <a href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
          </p>
        </li>
        <hr>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks!</p>
  {% endif %}

{% endblock %}

templates/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag</h1>
  <p>Do you want you delete tag <b>{{ tag }}</b>?</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{% url 'todo:tag-list' %}">No</a>
  </form>
{% endblock %}

templates/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h1>
      Tags
      <a style="float:right" class="btn btn-primary" href="{% url 'todo:tag-create' %}">Add</a>
    </h1>
  </div>
  <br>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a class="btn btn-secondary" href="{% url 'todo:tag-update' pk=tag.id %}">Update</a>
          </td>
          <td>
            <a class="btn btn-secondary" href="{% url 'todo:tag-delete' pk=tag.id %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags!</p>
  {% endif %}

{% endblock %}

templates/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task</h1>
  <p>Do you want you delete task <b>{{ task.content }}</b>?</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{% url 'todo:task-list' %}">No</a>
  </form>
{% endblock %}

templates/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}